server:
  port: 8081

spring:
  profiles:
    include: oauth, real-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect

  session:
    store-type: jdbc